#!/usr/bin/env python3
# ruff: noqa: F821
"""Simulate agents working on an attack graph.

Usage:
  simulate [options]

Options:
  --lang-file=<path>          Path to .mal or .mar file
  --model-file=<path>         Path to json/yml instance model file
  --horizon=<int|float>       Maximum number of steps to run the simulation for
  --start-step=<int>          When the attacker agent starts working
  --attacker=<type>           The attacker agent to use [default: bfs-random]
  --log-window=<int>          How many logs to use as history [default: 40]
  --fp-rate=<float>           False positive rate [default: 0.1]
  --iterations=<int>          How many simulations to run at once [default: 1]
  --sync                      Push sample files to Google Cloud Storage bucket

Notes:
  - The default for the --horizon parameter is to match the number of attack
    step in the attack graph plus 10%.

  - The default for the --start-step parameter is pick a random starting point
    between 0 and half the horizon.
"""

import logging
import random
import time
import zipfile
from pathlib import Path

import malsim.agents as agents
import yaml
from malsim.sims.mal_simulator import MalSimulator
from maltoolbox.attackgraph import AttackGraph
from maltoolbox.language import LanguageGraph
from maltoolbox.model import Model

from libexec.storage import GcsStorageBucket

l = logging.getLogger(__name__)

attacker_agents = {
    "passive": agents.PassiveAgent,
    "bfs-random": agents.BreadthFirstAttacker,
    "dfs-random": agents.DepthFirstAttacker,
}


def simulate() -> None:
    env = _get_env()

    # TODO: These should accept objects
    env.register_attacker("attacker", 0)

    # TODO: why is this needed at all?
    state = env.reset()["attacker"]

    l.info("Simulation started.")

    start_time = time.time()

    reported = False
    for timestep in range(x.horizon):
        stepstamp = "{:>{}}/{}".format(timestep, len(str(x.horizon)), x.horizon)

        if timestep % 1000 == 0:
            l.info(f"Timestep {stepstamp}. Time: {time.time() - start_time:.2f}s.")

        if timestep == x.start_step:
            l.info(f"Timestep {stepstamp}: Deploying {x.attacker} attacker.")
            attacker = attacker_agents[x.attacker](
                {
                    "randomize": True,
                    "attack_graph": env.attack_graph,
                    "wait_factor": 0 / 6,
                }
            )

        if timestep >= x.start_step and not state.terminated:
            # TODO check if timestep is still required to set here
            state.timestamp = timestep
            actions = _compute_action(attacker, state)
        else:
            # Emulate a passive attacker without creating one for the time steps
            # before an actual attacker agent (passive or other) is strictly
            # needed. Do that after the attacker has nothing left to do as well.
            actions = {"attacker": []}  # do nothing

        env.step(actions)

        state = env.get_agent_state("attacker")

        if state.terminated and not reported:
            reported = True
            l.info("Timestep %s: Attacker has nothing more to do.", timestep)

        if state.truncated:
            l.info("Simulation terminated by simulator.")
            break

    # TODO: doing this to write the logs to a file
    attacker.terminate()

    l.info(f"Simulation completed after: {time.time() - start_time:.2f}s")


def _get_env():
    try:
        lang_graph = LanguageGraph.from_mar_archive(x.lang_file)
    except zipfile.BadZipFile:
        lang_graph = LanguageGraph.from_mal_spec(x.lang_file)

    l.info("langgraph done")

    model = Model.load_from_file(x.model_file, lang_graph)
    l.info("model done")

    attack_graph = AttackGraph(lang_graph, model)
    attack_graph.save_to_file("tmp/ag.json")
    l.info("attack graph done")

    # TODO why is this needed?
    attack_graph.attach_attackers()

    if isinstance(x.horizon, float):
        x.horizon = int(x.horizon * len(attack_graph.nodes))

    if x.start_step == -1:
        x.start_step = random.randint(0, x.horizon // 2)

    env = MalSimulator(
        attack_graph,
        max_iter=x.horizon,
        prune_unviable_unnecessary=False,
        # TODO: this is needed for the random entry point selection
    )

    l.info("simulator created")
    return env


# TODO remove this function
def _compute_action(attacker, state):
    try:
        action = [attacker.get_next_action(state)]
    except KeyError:
        # This happens only after attacker termination/truncation
        action = []

    return {"attacker": action}


def _parse_args(kwargs: dict):
    with Path("config.yml").open(encoding="utf8") as f:
        conf = yaml.safe_load(f)

    kwargs.update(conf["common"])
    kwargs.update(conf.get(__epic_script__, {}))

    if not kwargs["horizon"]:
        kwargs["horizon"] = "1.1"

    if kwargs["horizon"].isnumeric():
        kwargs["horizon"] = int(kwargs["horizon"])
    else:
        try:
            kwargs["horizon"] = float(kwargs["horizon"])
        except TypeError:
            raise ValueError(
                "Expected int or float for horizon, got "
                f"{type(kwargs['horizon'])}: {kwargs['horizon']}"
            )

    kwargs["log_window"] = int(kwargs["log_window"])
    kwargs["fp_rate"] = float(kwargs["fp_rate"])
    kwargs["iterations"] = int(kwargs["iterations"])
    kwargs["data_folder"] = Path(kwargs["data_folder"])

    kwargs["start_step"] = (
        -1 if kwargs["start_step"] is None else int(kwargs["start_step"])
    )

    return kwargs


x = _parse_args(kwargs)

files = [simulate() for _ in range(x.iterations)]

if x.sync:
    l.info("Saving to bucket.")
    bucket = GcsStorageBucket(x.bucket_name, x.gcp_auth)
    for i, file in enumerate(files):
        if i % 10 == 0:
            l.info("Uploading file %d / %d", i, len(files))
        bucket.upload(file, file.relative_to(x.data_folder))
