studySpec:
  metrics:
  - metricId: F1
    goal: MAXIMIZE
  parameters:
  - parameterId: iterations
    integerValueSpec:
      minValue: 100
      maxValue: 1000
    scaleType: UNIT_LOG_SCALE
  - parameterId: compromised
    integerValueSpec:
      minValue: 64
      maxValue: 256
    scaleType: UNIT_LOG_SCALE
  - parameterId: uncompromised
    integerValueSpec:
      minValue: 64
      maxValue: 256
    scaleType: UNIT_LOG_SCALE
  - parameterId: val-samples
    integerValueSpec:
      minValue: 16
      maxValue: 32
    scaleType: UNIT_LOG_SCALE
  - parameterId: epochs
    integerValueSpec:
      minValue: 8
      maxValue: 32
    scaleType: UNIT_LOG_SCALE
  - parameterId: fp-rate
    doubleValueSpec:
      minValue: 0.005
      maxValue: 0.1
    scaleType: UNIT_LOG_SCALE
  - parameterId: learning-rate
    doubleValueSpec:
      minValue: 0.00005
      maxValue: 0.01
    scaleType: UNIT_LOG_SCALE
  - parameterId: hidden-layer1
    integerValueSpec:
      minValue: 256
      maxValue: 2048
    scaleType: UNIT_LOG_SCALE
  - parameterId: hidden-layer2
    integerValueSpec:
      minValue: 256
      maxValue: 2048
    scaleType: UNIT_LOG_SCALE
  - parameterId: hidden-layer3
    integerValueSpec:
      minValue: 256
      maxValue: 2048
    scaleType: UNIT_LOG_SCALE
  - parameterId: hidden-layer4
    integerValueSpec:
      minValue: 256
      maxValue: 2048
    scaleType: UNIT_LOG_SCALE
  - parameterId: edge_embedding_dim
    integerValueSpec:
      minValue: 256
      maxValue: 2048
    scaleType: UNIT_LOG_SCALE
  - parameterId: heads-per-layer
    integerValueSpec:
      minValue: 1
      maxValue: 8
    scaleType: UNIT_LOG_SCALE
trialJobSpec:
  workerPoolSpecs:
    - machineSpec:
        machineType: n1-highcpu-32
      replicaCount: 1
      containerSpec:
        imageUri: europe-north1-docker.pkg.dev/aps-validation-joarjox/heatmap-images/heatmap:latest
